name: Jekyll site CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the site in the jekyll/builder container
      mun: |
        docker run \
	--rm --security-opt label:disable \
	-v ${{ github.workspace }}:/srv/jekyll \
	-u $(id -u):100 -t gaow/lab-wiki sos run release.sos --no-use-docker
